### ISSUE TITLE
`Transaction.aborted` is checked but never set

### ISSUE THREAD

**Issue by gsps** [LPD-EPFL/CS453-2018-project#10]
See https://github.com/LPD-EPFL/CS453-2018-project/blob/master/grading/grading.cpp#L365 ; aborted should be set on failed reads and writes. (Transaction-typed members are even marked const in most places.)

**Comment by srlt** [comment]
You are entirely right. Thank you again!

It should be corrected in commit 093747576c785139f0bd8ab136ab165afc1059a9.
