### ISSUE TITLE
Exception when running ./grading 

### ISSUE THREAD

**Issue by sabetAI** [LPD-EPFL/CS453-2018-project#11]
When running
./grading 3 ../reference.so ../<my student number>.so

What does it mean if it outputs:
...
⎪ *** EXCEPTION - main thread ***
⎩ grading: symbol not found in loaded libraries

**Comment by srlt** [comment]
It means that one of the library you specified in the command line (your output has been truncated so I can't tell which one in your case) does not export some of the `tm_*` functions.

Make sure that you define in your source code each and every function found in subsection _Interface specification/Reference_ of `README.md`, including `tm_alloc` and `tm_free` that you can left "empty" for the first step of the project (as in the template code).

Then check with `objdump` (or similar like `readelf`, `nm`, ...) that your library indeed exports all the symbols `tm_*`. For instance with `reference.so`, you should see something like:
```sh
$ objdump -t reference.so | grep " tm_"
0000000000000c40 g     F .text	0000000000000044              tm_begin
0000000000000c30 g     F .text	0000000000000005              tm_align
0000000000000cd0 g     F .text	000000000000001c              tm_write
0000000000000cb0 g     F .text	000000000000001c              tm_read
0000000000000cf0 g     F .text	000000000000009e              tm_alloc
0000000000000af0 g     F .text	00000000000000bd              tm_create
0000000000000d90 g     F .text	0000000000000036              tm_free
0000000000000c20 g     F .text	0000000000000005              tm_size
0000000000000c10 g     F .text	0000000000000005              tm_start
0000000000000bb0 g     F .text	000000000000005b              tm_destroy
0000000000000c90 g     F .text	0000000000000013              tm_end
```

Reopen if you followed these steps successfuly but still have issues.
