### ISSUE TITLE
Submission failure output

### ISSUE THREAD

**Issue by vincenzobaz** [LPD-EPFL/CS453-2018-project#15]
Would it be possible to have more informative information in case of failure on the evaluation machine?

Locally everything works, however when I submit I get:
`Your submission could not run (at all or in part) on the server.`

**Comment by vincenzobaz** [comment]
`python3 submit.py --uuid "myCorrectUUID" sub.zip`
gives
```
Your submission has been queued on the server. Please wait.
Your submission is compiling on the server. Please wait.
cc -Wall -Wextra -Wfatal-errors -O2 -std=c11 -fPIC -I../include -c -o morecfiles
cc -Wall -Wextra -Wfatal-errors -O2 -std=c11 -fPIC -I../include -c -o tm.c.o tm.c
cc -Wall -Wextra -Wfatal-errors -O2 -std=c11 -fPIC -I../include -c -o morecfiles
cc -shared -o ../SCIPER.so ./CFILEA.c.o ./tm.c.o ./CFILEB.c.o  
Traceback (most recent call last):
  File "submit.py", line 215, in <module>
    sys.stdout.write(data.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 255: unexpected end of data
```
It seems that the server is sending some data the submit.py does not know how to parse. Am I doing something wrong?

**Comment by srlt** [comment]
Nothing wrong on your side.
You are simply unlucky: data is transmitted back by blocks of 256 bytes,
and it just happens in your case that a multibytes UTF-8 character get split
(apparently, this one: `‘`; encoded into `e2 80 98`).

For now you could simply remove the `decode` call.
This is a bug of `submit.py`, that I will correct (and then close this issue).

**Comment by srlt** [comment]
> Would it be possible to have more informative information in case of failure on the evaluation machine?

You get the message `Your submission could not run (at all or in part) on the server.` when the execution of `grading` returned a non-zero code.
The actual cause of the error is unknown to the server, which simply forwards the standard output and error to the client (you).

So to know more, you would need the content of `stdout` and `stderr`.

**Comment by srlt** [comment]
Should be corrected in commit 5f17fc9e7c202febee51d3e8fdc1224e5ea3105a.

**Comment by vincenzobaz** [comment]
> You get the message `Your submission could not run (at all or in part) on the server.` when the execution of grading returned a non-zero code.

Would it be possible to know if the problem are inconsistencies or timeout ?

**Comment by srlt** [comment]
If you don't see any message, then this is a timeout.
