### ISSUE TITLE
Add extern "C" to tm.h

### ISSUE THREAD

**Issue by atrib** [LPD-EPFL/CS453-2018-project#8]
Suggestion: Enclose the function prototypes in **tm.h** in **extern "C" { ... }**.

For people planning to implement in C++, this would remove the need to enclose the **#include <tm.h>** line in **extern "C" { ... }** in their implementation cpp file. 

As of now, implementations need to have something like below:
```
extern "C" { 
#include "tm.h"
...
shared_t tm_create( ... ) {

}

}
```
instead of 
```
#include "tm.h"
...
extern "C" { 
shared_t tm_create( ... ) {

}

}
```

**Comment by srlt** [comment]
I see your point. Thanks for sharing it.

For the record:
I guess it is entirely a matter of appreciating who should be responsible for what.
I think the C++ developer should be aware she/he is including C code⁽¹⁾, which might not be valid C++ (this is my key argument, see C11 `_Atomic` keyword for instance), and acts appropriately.
So I'd like to keep it to the current state.

⁽¹⁾ Perhaps it is a bad habit of mine, but I use `*.h` for C headers and `*.hpp` for C++ ones.
