### ISSUE TITLE
`Bank` workload initializer should retry on failed transaction

### ISSUE THREAD

**Issue by gsps** [LPD-EPFL/CS453-2018-project#9]
Instead of retrying initialization of the global state, the `Bank` workload will happily start running even if initialization failed.

The do...while's condition should be `true` rather than `false` here:
https://github.com/LPD-EPFL/CS453-2018-project/blame/master/grading/grading.cpp#L467

**Comment by srlt** [comment]
That's right. Thanks!
Corrected in commit 18f951a75050bd1e9e8f33691df21f35bdc9c7dd.
